import { createClient } from '@supabase/supabase-js'

const RAIN_CODES = new Set([51,53,55,56,57,61,63,65,66,67,80,81,82,95,96,99])
const UNSAFE_CODES = new Set([45,48,71,73,75,77,85,86,95,96,99])
const STALE_MINUTES = 30

function client(){
  const url = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if(!url || !key) throw new Error('Missing Supabase env vars')
  return createClient(url,key)
}
async function fetchWeather(latitude, longitude){
  const url = new URL('https://api.open-meteo.com/v1/forecast')
  url.search = new URLSearchParams({latitude,longitude,current:'temperature_2m,apparent_temperature,relative_humidity_2m,precipitation,rain,showers,weather_code,wind_speed_10m,wind_gusts_10m',timezone:'auto'}).toString()
  const res = await fetch(url); if(!res.ok) throw new Error(`Open-Meteo failed ${res.status}`)
  const data=await res.json(), c=data.current||{}, observedAt=c.time?new Date(c.time):new Date()
  return {temperature:Number(c.temperature_2m??0),apparentTemperature:Number(c.apparent_temperature??c.temperature_2m??0),humidity:Number(c.relative_humidity_2m??0),precipitation:Number(c.precipitation??0),rain:Number(c.rain??0),showers:Number(c.showers??0),weatherCode:Number(c.weather_code??0),windSpeed:Number(c.wind_speed_10m??0),windGusts:Number(c.wind_gusts_10m??0),observedAt:observedAt.toISOString(),isStale:Date.now()-observedAt.getTime()>STALE_MINUTES*60*1000}
}
function weatherDecision(w){
  const precipitation=Number(w.precipitation||0)+Number(w.rain||0)+Number(w.showers||0), rain=precipitation>0||RAIN_CODES.has(Number(w.weatherCode)), hot=Number(w.apparentTemperature)>=35, cold=Number(w.apparentTemperature)<=18||(Number(w.temperature)<=22&&Number(w.windSpeed)>=18), windy=Number(w.windSpeed)>=25||Number(w.windGusts)>=35, humid=Number(w.humidity)>=85, unsafe=UNSAFE_CODES.has(Number(w.weatherCode))
  if(w.isStale) return {recommended_trigger_type:null,shouldChangeState:false,confidence:.35,status:'stale_weather',reason:'Weather data is stale; kept last known state.'}
  if(rain) return {recommended_trigger_type:'weather_rainy',shouldChangeState:true,confidence:.96,status:'rain_priority',reason:`Rain/storm detected: precipitation ${precipitation.toFixed(1)}mm, code ${w.weatherCode}. Rain beats heat.`}
  if(hot&&!windy&&!humid) return {recommended_trigger_type:'weather_hot',shouldChangeState:true,confidence:.9,status:'hot_safe',reason:`Feels-like ${w.apparentTemperature.toFixed(1)}°C, no rain, wind ${w.windSpeed.toFixed(1)}km/h and humidity ${w.humidity}% are acceptable.`}
  if(cold) return {recommended_trigger_type:'weather_cold',shouldChangeState:true,confidence:.82,status:'cold_windy',reason:`Cold/breezy signal: feels-like ${w.apparentTemperature.toFixed(1)}°C and wind ${w.windSpeed.toFixed(1)}km/h.`}
  if(unsafe||windy||humid) return {recommended_trigger_type:'weather_normal',shouldChangeState:true,confidence:.74,status:'safe_default',reason:`Weather not ideal for hot creative: wind ${w.windSpeed.toFixed(1)}km/h, humidity ${w.humidity}%, code ${w.weatherCode}. Safe default selected.`}
  return {recommended_trigger_type:'weather_normal',shouldChangeState:true,confidence:.78,status:'normal',reason:'No strong rain, heat, or cold trigger matched. Generic creative is safest.'}
}
function nowBetween(s,e){return s&&e&&new Date()>=new Date(s)&&new Date()<=new Date(e)}
function nonWeather(item){const cfg=item.condition_config||{}; if(item.trigger_type==='festival'){const met=nowBetween(cfg.start_date,cfg.end_date);return{trigger_name:'FestivalTrigger',condition_met:met,confidence:met?.9:.3,reason:met?`${cfg.festival_name||'Festival'} is live.`:`${cfg.festival_name||'Festival'} is not live.`}} if(item.trigger_type==='cricket_match'){const met=nowBetween(cfg.match_start,cfg.match_end);return{trigger_name:'CricketTrigger',condition_met:met,confidence:met?.82:.3,reason:met?`Cricket window is live: ${cfg.teams||''}.`:'Cricket window is not live.'}} if(item.trigger_type==='stock_market'||item.trigger_type==='forex'){const val=Number(cfg.last_value||0),th=Number(cfg.threshold||0),met=cfg.direction==='below'?val<=th:val>=th;return{trigger_name:item.trigger_type==='forex'?'ForexTrigger':'StockTrigger',condition_met:met,confidence:met?.75:.3,reason:`${cfg.ticker||cfg.pair||'Market'} value ${val}, threshold ${th}.`}} if(item.trigger_type==='manual'||item.trigger_type==='custom'){const met=cfg.enabled===true||cfg.enabled==='true';return{trigger_name:cfg.trigger_name||'ManualTrigger',condition_met:met,confidence:met?Number(cfg.confidence||1):.2,reason:met?(cfg.reason||'Manual/custom trigger enabled.'):'Manual/custom trigger disabled.'}} return{condition_met:false,confidence:0,reason:'Unsupported trigger'}}
function pick(items,wd){const nw=items.filter(i=>!String(i.trigger_type).startsWith('weather_')).map(i=>({item:i,res:nonWeather(i)})).filter(x=>x.res.condition_met).sort((a,b)=>(b.item.priority||0)-(a.item.priority||0)||b.res.confidence-a.res.confidence); if(nw.length)return{winner:nw[0].item,result:nw[0].res,status:'non_weather_trigger'}; if(!wd.shouldChangeState)return{winner:null,result:wd,status:wd.status}; const winner=items.find(i=>i.trigger_type===wd.recommended_trigger_type)||items.find(i=>i.trigger_type==='weather_normal'); return{winner,result:{trigger_name:'WeatherTrigger',condition_met:true,confidence:wd.confidence,reason:wd.reason},status:wd.status}}
async function due(db){const {data}=await db.from('app_config').select('*').eq('key','sync_settings').maybeSingle(); const cfg=data?.value||{interval_minutes:5,auto_sync_enabled:true}; if(cfg.auto_sync_enabled===false)return{ok:false,cfg,why:'auto sync disabled'}; const last=cfg.last_auto_sync_at?new Date(cfg.last_auto_sync_at).getTime():0; const mins=Number(cfg.interval_minutes||5); return{ok:Date.now()-last>=mins*60*1000,cfg,why:`interval ${mins} min`}}
async function run(){const db=client(); const d=await due(db); if(!d.ok)return{skipped:true,reason:d.why}; const {data:campaigns}=await db.from('campaigns').select('*').eq('state','active'); if(!campaigns?.length)return{skipped:true,reason:'campaign paused'}; const {data:cities,error}=await db.from('cities').select('*').eq('is_active',true); if(error)throw error; const results=[]; for(const c of cities||[]){try{const w=await fetchWeather(c.latitude,c.longitude),wd=weatherDecision(w); await db.from('city_weather_cache').upsert({city:c.city,latitude:c.latitude,longitude:c.longitude,temperature:w.temperature,apparent_temperature:w.apparentTemperature,precipitation:w.precipitation,humidity:w.humidity,wind_speed:w.windSpeed,weather_code:w.weatherCode,recommended_trigger_type:wd.recommended_trigger_type,decision_reason:wd.reason,confidence:wd.confidence,fetched_at:new Date().toISOString()},{onConflict:'city'}); const {data:items}=await db.from('line_items').select('*').eq('city',c.city).order('priority',{ascending:false}); const {winner,result,status}=pick(items||[],wd); if(!winner){results.push({city:c.city,status:'no_line_items'}); continue} for(const item of items||[]){const newState=item.id===winner.id?'active':'paused'; const payload={state:newState,last_weather_temperature:w.temperature,last_weather_apparent_temperature:w.apparentTemperature,last_weather_humidity:w.humidity,last_weather_wind_speed:w.windSpeed,last_weather_code:w.weatherCode,last_weather_precipitation:w.precipitation,last_decision_reason:result.reason,last_decision_confidence:result.confidence,sync_status:status,updated_at:new Date().toISOString()}; await db.from('line_items').update(payload).eq('id',item.id); if(item.state!==newState) await db.from('transition_logs').insert({line_item_id:item.id,city:item.city,creative_name:item.creative_name,previous_state:item.state,new_state:newState,reason:result.reason,trigger_name:result.trigger_name,weather_temperature:w.temperature,weather_apparent_temperature:w.apparentTemperature,weather_humidity:w.humidity,weather_wind_speed:w.windSpeed,weather_code:w.weatherCode,weather_precipitation:w.precipitation,confidence:result.confidence})} results.push({city:c.city,status:'success',activeCreative:winner.creative_name})}catch(e){await db.from('line_items').update({sync_status:'api_failed_keep_last_state',last_decision_reason:`Weather/API sync failed. Keeping last known state. ${e.message}`,updated_at:new Date().toISOString()}).eq('city',c.city); results.push({city:c.city,status:'failed',reason:e.message})}} const cfg=d.cfg||{}; await db.from('app_config').upsert({key:'sync_settings',value:{...cfg,last_auto_sync_at:new Date().toISOString()},updated_at:new Date().toISOString()}); return{results}}
export default async function handler(){try{return new Response(JSON.stringify(await run()),{status:200,headers:{'content-type':'application/json'}})}catch(e){return new Response(JSON.stringify({error:e.message}),{status:500,headers:{'content-type':'application/json'}})}}
export const config = { schedule: '* * * * *' }
