import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { CloudRain, Flame, Snowflake, RefreshCcw, Upload, LogOut, Eye, ShieldCheck, Plus, MapPin, Trophy, TrendingUp, PartyPopper, SlidersHorizontal, ShoppingBag, UserCircle, Sparkles, Wind, Droplets, Sun, Pencil, CheckCircle2, Globe2, CloudSun, Gauge, MessageCircle, Clock, Settings, CloudLightning, Leaf } from 'lucide-react'
import './styles.css'
import { supabase, isSupabaseConfigured } from './lib/supabase'
import { runContextSync, TRIGGER_TYPES, fetchWeather, getWeatherRecommendation } from './lib/triggerEngine'

const campaignId='11111111-1111-1111-1111-111111111111'
const fmt=d=>d?new Date(d).toLocaleString():'Never'
const json=v=>{try{return JSON.stringify(v||{},null,2)}catch{return '{}'}}
function hav(a,b){const R=6371,dLat=(+b.latitude-+a.latitude)*Math.PI/180,dLon=(+b.longitude-+a.longitude)*Math.PI/180,lat1=+a.latitude*Math.PI/180,lat2=+b.latitude*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function EmptyConfig(){return <div className="min-h-screen grid place-items-center bg-slate-950 text-white p-6"><div className="card-dark"><h1 className="text-3xl font-black">DynaMo setup needed</h1><p className="mt-3 text-slate-300">Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env, save, then restart npm run dev.</p></div></div>}
function Login({onLogin}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');async function login(e){e.preventDefault();setError('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);else onLogin()}return <div className="min-h-screen bg-gradient-to-br from-orange-50 to-cyan-50 grid place-items-center p-4"><form onSubmit={login} className="w-full max-w-md bg-white rounded-3xl shadow-xl p-8 border"><div className="h-12 w-12 bg-orange-500 rounded-2xl grid place-items-center text-white mb-4"><ShieldCheck/></div><h1 className="text-3xl font-black">DynaMo Admin</h1><p className="text-slate-500">Decision center for context-aware ads.</p><input className="input mt-6" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="input mt-3" placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}<button className="btn-primary w-full mt-5">Login</button></form></div>}
function defaultConfig(t){if(t==='cricket_match')return '{"teams":"","match_start":"","match_end":""}';if(t==='stock_market')return '{"ticker":"","direction":"above","threshold":0,"last_value":0}';if(t==='forex')return '{"pair":"USDINR","direction":"above","threshold":0,"last_value":0}';if(t==='festival')return '{"festival_name":"","start_date":"","end_date":""}';if(t==='manual'||t==='custom')return '{"enabled":true,"reason":""}';if(t==='weather_hot')return '{"min_apparent_temperature":35,"max_wind_kmh":25,"max_humidity":85}';if(t==='weather_rainy')return '{"precipitation_gt":0,"priority_reason":"rain beats heat"}';if(t==='weather_cold')return '{"max_apparent_temperature":18,"windy_is_ok":true}';return '{"safe_default":true}'}
function family(t){return t?.startsWith('weather')?'weather':t?.startsWith('cricket')?'cricket':t?.startsWith('stock')?'stock':t?.startsWith('festival')?'festival':t==='forex'?'forex':t==='custom'?'custom':'manual'}
function TriggerBadge({t}){const I=t?.includes('rain')?CloudRain:t?.includes('hot')?Flame:t?.includes('cold')?Snowflake:t?.includes('cricket')?Trophy:t?.includes('stock')||t?.includes('forex')?TrendingUp:t?.includes('festival')?PartyPopper:RefreshCcw;return <span className="badge"><I size={14}/>{t}</span>}
function WeatherIcon({cache}){const t=cache?.recommended_trigger_type||'';if(t.includes('rain'))return <Droplets className="text-sky-500"/>;if(t.includes('hot'))return <Sun className="text-yellow-500"/>;if(t.includes('cold'))return <Snowflake className="text-blue-500"/>;if(Number(cache?.wind_speed)>=18)return <Wind className="text-emerald-500"/>;return <CloudSun className="text-orange-400"/>}
function confidenceText(v){return v!==null&&v!==undefined?`${Math.round(Number(v)*100)}%`:'-'}

function Dashboard(){
const[items,setItems]=useState([]),[logs,setLogs]=useState([]),[cities,setCities]=useState([]),[weatherCards,setWeatherCards]=useState([]),[campaign,setCampaign]=useState(null),[seasonal,setSeasonal]=useState([]),[config,setConfig]=useState({interval_minutes:5,auto_sync_enabled:true}),[feedback,setFeedback]=useState([])
const[city,setCity]=useState('All'),[state,setState]=useState('All'),[trigger,setTrigger]=useState('All'),[msg,setMsg]=useState(''),[syncing,setSyncing]=useState(false),[uploading,setUploading]=useState('')
const[newCity,setNewCity]=useState({city:'',latitude:'',longitude:''})
const[newItem,setNewItem]=useState({creative_name:'',city:'Mumbai',trigger_type:'manual',priority:75,bid:1.2,daily_budget:50,condition_config:defaultConfig('manual')})
const[template,setTemplate]=useState({trigger_type:'weather_rainy',creative_name:'Rainy day pick-me-up',creative_image_url:'',priority:100,condition_config:defaultConfig('weather_rainy')})
const[editing,setEditing]=useState(null),[editConfig,setEditConfig]=useState('')
async function load(){const[{data:i},{data:l},{data:c},{data:camp},{data:s},{data:w},{data:cfg},{data:fb}]=await Promise.all([
 supabase.from('line_items').select('*').order('city').order('priority',{ascending:false}),
 supabase.from('transition_logs').select('*').order('created_at',{ascending:false}).limit(30),
 supabase.from('cities').select('*').eq('is_active',true).order('city'),
 supabase.from('campaigns').select('*').eq('id',campaignId).maybeSingle(),
 supabase.from('seasonal_creatives').select('*').order('priority',{ascending:false}),
 supabase.from('city_weather_cache').select('*').order('city'),
 supabase.from('app_config').select('*').eq('key','sync_settings').maybeSingle(),
 supabase.from('user_weather_feedback').select('*').order('created_at',{ascending:false}).limit(20)
]);setItems(i||[]);setLogs(l||[]);setCities(c||[]);setCampaign(camp);setSeasonal(s||[]);setWeatherCards(w||[]);setConfig(cfg?.value||{interval_minutes:5,auto_sync_enabled:true});setFeedback(fb||[]);if(c?.length&&!c.find(x=>x.city===newItem.city))setNewItem(v=>({...v,city:c[0].city}))}
useEffect(()=>{load();const ch=supabase.channel('admin-live').on('postgres_changes',{event:'*',schema:'public',table:'line_items'},load).on('postgres_changes',{event:'*',schema:'public',table:'cities'},load).on('postgres_changes',{event:'*',schema:'public',table:'campaigns'},load).on('postgres_changes',{event:'*',schema:'public',table:'city_weather_cache'},load).on('postgres_changes',{event:'*',schema:'public',table:'app_config'},load).on('postgres_changes',{event:'*',schema:'public',table:'user_weather_feedback'},load).subscribe();return()=>supabase.removeChannel(ch)},[])
useEffect(()=>{if(!config.auto_sync_enabled)return;const mins=Number(config.interval_minutes||5);const id=setInterval(()=>syncNow('auto'),Math.max(1,mins)*60*1000);return()=>clearInterval(id)},[config.interval_minutes,config.auto_sync_enabled])
const filtered=items.filter(i=>(city==='All'||i.city===city)&&(state==='All'||i.state===state)&&(trigger==='All'||i.trigger_type===trigger));const cards=useMemo(()=>({total:items.length,active:items.filter(i=>i.state==='active').length,paused:items.filter(i=>i.state==='paused').length,cities:cities.length,last:items.map(i=>i.updated_at).sort().at(-1)}),[items,cities])
async function syncNow(source='manual'){setSyncing(true);setMsg('');try{const r=await runContextSync();setMsg(`${source==='auto'?'Auto':'Manual'} sync applied: `+r.map(x=>`${x.city}:${x.status}`).join(', '));await load()}catch(e){setMsg(e.message)}setSyncing(false)}
async function saveSyncSettings(e){e.preventDefault();const value={...config,interval_minutes:Number(config.interval_minutes||5),auto_sync_enabled:Boolean(config.auto_sync_enabled)};await supabase.from('app_config').upsert({key:'sync_settings',value,updated_at:new Date().toISOString()});setMsg(`Auto sync ${value.auto_sync_enabled?'enabled':'disabled'} every ${value.interval_minutes} min. Netlify checks every minute and only syncs when due.`);await load()}
async function toggleCampaign(){const next=campaign?.state==='paused'?'active':'paused';await supabase.from('campaigns').update({state:next}).eq('id',campaignId);if(next==='paused')await supabase.from('line_items').update({state:'paused',sync_status:'campaign_paused',last_decision_reason:'Campaign paused from admin.',updated_at:new Date().toISOString()}).eq('campaign_id',campaignId);setMsg(`Campaign ${next}.`);await load()}
async function toggleItem(item){const next=item.state==='active'?'paused':'active';if(next==='active')await supabase.from('line_items').update({state:'paused',sync_status:'manual_override',last_decision_reason:`Paused because ${item.creative_name} was manually activated for ${item.city}.`,updated_at:new Date().toISOString()}).eq('city',item.city).eq('state','active');await supabase.from('line_items').update({state:next,sync_status:'manual_override',last_decision_reason:next==='active'?'Creative manually activated from admin.':'Creative manually paused from admin.',last_decision_confidence:1,updated_at:new Date().toISOString()}).eq('id',item.id);await supabase.from('transition_logs').insert({line_item_id:item.id,city:item.city,creative_name:item.creative_name,previous_state:item.state,new_state:next,reason:'Manual admin action.',trigger_name:'AdminOverride',confidence:1});await load()}
async function upload(pathPrefix,file){if(!file)return null;const path=`${pathPrefix}/${Date.now()}-${file.name}`;const{error}=await supabase.storage.from('creatives').upload(path,file,{upsert:true});if(error)throw error;return supabase.storage.from('creatives').getPublicUrl(path).data.publicUrl}
async function addCity(e){e.preventDefault();const cityName=newCity.city.trim();if(!cityName)return;const lat=Number(newCity.latitude),lon=Number(newCity.longitude);const{error}=await supabase.from('cities').insert({city:cityName,latitude:lat,longitude:lon,is_active:true});if(error){setMsg(error.message);return}await applyTemplatesToCity({city:cityName,latitude:lat,longitude:lon});setMsg(`${cityName} added. It appears in public dropdown through realtime and gets weather on next sync.`);setNewCity({city:'',latitude:'',longitude:''});await syncNow('new-city')}
async function applyTemplatesToCity(c){const rows=(seasonal||[]).filter(s=>s.is_active).map(s=>({campaign_id:s.campaign_id,seasonal_creative_id:s.id,creative_id:`${s.trigger_type}-${c.city.toLowerCase()}`,creative_name:s.creative_name,creative_image_url:s.creative_image_url,city:c.city,latitude:c.latitude,longitude:c.longitude,trigger_type:s.trigger_type,condition_config:s.condition_config,priority:s.priority,state:s.trigger_type==='weather_normal'?'active':'paused',bid:1.2,daily_budget:50,last_decision_reason:'Created automatically from global seasonal creative.'}));if(rows.length)await supabase.from('line_items').upsert(rows,{onConflict:'city,trigger_type,creative_id'})}
async function addLineItem(e){e.preventDefault();let cfg;try{cfg=JSON.parse(newItem.condition_config)}catch{return setMsg('Condition config JSON is invalid.')}const c=cities.find(x=>x.city===newItem.city);if(!c)return setMsg('Choose a valid city.');let init=(await supabase.from('initiatives').insert({campaign_id:campaignId,name:newItem.creative_name||newItem.trigger_type,trigger_family:family(newItem.trigger_type),description:'Created from admin add initiative form.'}).select().single()).data;const row={campaign_id:campaignId,initiative_id:init.id,creative_id:`${newItem.trigger_type}-${newItem.city}-${Date.now()}`,creative_name:newItem.creative_name,creative_image_url:'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=1200&auto=format&fit=crop',city:c.city,latitude:c.latitude,longitude:c.longitude,trigger_type:newItem.trigger_type,condition_config:cfg,priority:Number(newItem.priority),state:'paused',bid:Number(newItem.bid),daily_budget:Number(newItem.daily_budget),last_decision_reason:'Created via Add initiative. Click Apply to evaluate.'};const{error}=await supabase.from('line_items').insert(row);if(error)setMsg(error.message);else{setMsg('Initiative created. Click Apply to evaluate it.');await load()}}
async function applySeasonal(e){e.preventDefault();let cfg;try{cfg=JSON.parse(template.condition_config)}catch{return setMsg('Season condition JSON is invalid.')}if(!template.creative_image_url)return setMsg('Upload or paste an image URL first.');const{data:s,error}=await supabase.from('seasonal_creatives').upsert({campaign_id:campaignId,trigger_type:template.trigger_type,creative_name:template.creative_name,creative_image_url:template.creative_image_url,condition_config:cfg,priority:Number(template.priority),is_active:true,updated_at:new Date().toISOString()},{onConflict:'campaign_id,trigger_type'}).select().single();if(error)return setMsg(error.message);const rows=cities.map(c=>({campaign_id:campaignId,seasonal_creative_id:s.id,creative_id:`${s.trigger_type}-${c.city.toLowerCase()}`,creative_name:s.creative_name,creative_image_url:s.creative_image_url,city:c.city,latitude:c.latitude,longitude:c.longitude,trigger_type:s.trigger_type,condition_config:s.condition_config,priority:s.priority,state:'paused',bid:1.2,daily_budget:50,last_decision_reason:'Updated from global seasonal creative template.',updated_at:new Date().toISOString()}));await supabase.from('line_items').upsert(rows,{onConflict:'city,trigger_type,creative_id'});setMsg(`${s.creative_name} applied to ${cities.length} cities.`);await syncNow('template')}
async function uploadTemplateFile(file){try{setUploading('template');const url=await upload('seasonal',file);setTemplate(v=>({...v,creative_image_url:url}));}catch(e){setMsg(e.message)}finally{setUploading('')}}
async function saveConfig(item){let cfg;try{cfg=JSON.parse(editConfig)}catch{return setMsg('Invalid JSON.')}await supabase.from('line_items').update({condition_config:cfg,updated_at:new Date().toISOString()}).eq('id',item.id);setEditing(null);setMsg('Condition updated. Click Apply to re-evaluate.');await load()}
return <div className="min-h-screen bg-slate-50"><header className="bg-slate-950 text-white px-6 py-4 flex justify-between"><div><h1 className="text-2xl font-black">DynaMo Admin</h1><p className="text-slate-400 text-sm">Auto weather sync + city decision center</p></div><button className="btn" onClick={()=>supabase.auth.signOut().then(()=>location.reload())}><LogOut size={16}/>Logout</button></header><main className="p-5 max-w-[1500px] mx-auto">{msg&&<div className="notice">{msg}</div>}
<section className="grid md:grid-cols-5 gap-4">{[['Total',cards.total],['Active',cards.active],['Paused',cards.paused],['Cities',cards.cities],['Last sync',fmt(config.last_auto_sync_at||cards.last)]].map(([a,b])=><div className="card" key={a}><p className="text-sm text-slate-500">{a}</p><p className="text-2xl font-black">{b}</p></div>)}</section>
<div className="grid xl:grid-cols-3 gap-5 mt-5"><form onSubmit={saveSyncSettings} className="card"><h2 className="title"><Clock/>Auto sync settings</h2><p className="hint">Hosted Netlify function checks every minute and runs sync when this interval is due. Default is 5 minutes.</p><div className="grid grid-cols-2 gap-3 mt-4"><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={!!config.auto_sync_enabled} onChange={e=>setConfig({...config,auto_sync_enabled:e.target.checked})}/> Auto sync</label><input className="input" type="number" min="1" value={config.interval_minutes||5} onChange={e=>setConfig({...config,interval_minutes:e.target.value})}/></div><button className="btn-primary mt-4"><Settings/>Save timing</button><button type="button" onClick={()=>syncNow()} disabled={syncing} className="btn mt-4 ml-2"><RefreshCcw/> {syncing?'Syncing':'Run now'}</button></form>
<form onSubmit={addCity} className="card"><h2 className="title"><MapPin/>Add city</h2><p className="hint">Real Supabase insert. Public dropdown updates in realtime and templates are applied automatically.</p><div className="grid md:grid-cols-3 gap-3 mt-4"><input className="input" placeholder="City" value={newCity.city} onChange={e=>setNewCity({...newCity,city:e.target.value})}/><input className="input" placeholder="Latitude" value={newCity.latitude} onChange={e=>setNewCity({...newCity,latitude:e.target.value})}/><input className="input" placeholder="Longitude" value={newCity.longitude} onChange={e=>setNewCity({...newCity,longitude:e.target.value})}/></div><button className="btn-primary mt-4"><Plus/>Add city</button></form>
<div className="card"><h2 className="title"><Globe2/>Weather API</h2><p className="hint"><b>Open-Meteo</b> is used because it is free, requires no API key, and gives temperature, feels-like, rain, humidity, wind, gusts, and weather code. Confidence is rule-based: rain 96%, heat 90%, cold 82%, normal/safe default 74–78%.</p><button onClick={toggleCampaign} className={campaign?.state==='active'?'btn-danger mt-4':'btn mt-4'}>{campaign?.state==='active'?'Pause campaign':'Activate campaign'}</button></div></div>
<div className="card mt-5"><h2 className="title"><CloudSun/>Live city weather cards</h2><p className="hint">These cards are for your team only. Customer website does not show this technical data.</p><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4 mt-4">{cities.map(c=>{const w=weatherCards.find(x=>x.city===c.city);return <div className="city-weather-card" key={c.city}><div className="flex justify-between"><div><p className="text-sm text-slate-500">{c.city}</p><h3 className="text-2xl font-black">{w?.temperature??'-'}°C</h3></div><WeatherIcon cache={w}/></div><div className="grid grid-cols-2 gap-2 text-xs mt-3"><span>Feels: <b>{w?.apparent_temperature??'-'}°C</b></span><span>Rain: <b>{w?.precipitation??'-'}mm</b></span><span>Wind: <b>{w?.wind_speed??'-'} km/h</b></span><span>Humidity: <b>{w?.humidity??'-'}%</b></span><span>Code: <b>{w?.weather_code??'-'}</b></span><span>Confidence: <b>{confidenceText(w?.confidence)}</b></span></div><p className="text-xs mt-3 text-slate-600"><b>Why:</b> {w?.decision_reason||'Not synced yet.'}</p><p className="text-xs text-slate-400 mt-2">Fetched: {fmt(w?.fetched_at)}</p></div>})}</div></div>
<form onSubmit={applySeasonal} className="card mt-5"><h2 className="title"><CloudRain/>Global seasonal creative template</h2><p className="hint">Upload once for rainy/hot/cold/normal. Apply creates/updates line items for every city. If a city is raining, that city uses rainy creative after sync.</p><div className="grid md:grid-cols-4 gap-3 mt-4"><select className="input" value={template.trigger_type} onChange={e=>setTemplate({...template,trigger_type:e.target.value,condition_config:defaultConfig(e.target.value)})}>{TRIGGER_TYPES.filter(t=>t.value.startsWith('weather_')).map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select><input className="input" placeholder="Creative name" value={template.creative_name} onChange={e=>setTemplate({...template,creative_name:e.target.value})}/><input className="input" placeholder="Priority" value={template.priority} onChange={e=>setTemplate({...template,priority:e.target.value})}/><label className="btn cursor-pointer"><Upload/> {uploading==='template'?'Uploading':'Upload image'}<input type="file" accept="image/*" className="hidden" onChange={e=>uploadTemplateFile(e.target.files[0])}/></label></div><input className="input mt-3" placeholder="or paste image URL" value={template.creative_image_url} onChange={e=>setTemplate({...template,creative_image_url:e.target.value})}/><textarea className="input mt-3 font-mono text-xs" rows="3" value={template.condition_config} onChange={e=>setTemplate({...template,condition_config:e.target.value})}/><button className="btn-primary mt-4"><CheckCircle2/>Apply to all cities</button></form>
<form onSubmit={addLineItem} className="card mt-5"><h2 className="title"><SlidersHorizontal/>Add initiative / trigger</h2><p className="hint">Functionality is ready for festival, IPL/cricket, stock, forex, manual and custom rules. Nothing is pre-added; you create them when needed.</p><div className="grid md:grid-cols-3 gap-3 mt-4"><input className="input" placeholder="Creative name" value={newItem.creative_name} onChange={e=>setNewItem({...newItem,creative_name:e.target.value})}/><select className="input" value={newItem.city} onChange={e=>setNewItem({...newItem,city:e.target.value})}>{cities.map(c=><option key={c.city}>{c.city}</option>)}</select><select className="input" value={newItem.trigger_type} onChange={e=>setNewItem({...newItem,trigger_type:e.target.value,condition_config:defaultConfig(e.target.value)})}>{TRIGGER_TYPES.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select><input className="input" placeholder="Priority" value={newItem.priority} onChange={e=>setNewItem({...newItem,priority:e.target.value})}/><input className="input" placeholder="Bid" value={newItem.bid} onChange={e=>setNewItem({...newItem,bid:e.target.value})}/><input className="input" placeholder="Daily budget" value={newItem.daily_budget} onChange={e=>setNewItem({...newItem,daily_budget:e.target.value})}/></div><textarea className="input mt-3 font-mono text-xs" rows="3" value={newItem.condition_config} onChange={e=>setNewItem({...newItem,condition_config:e.target.value})}/><button className="btn-primary mt-4"><Plus/>Create initiative</button><button type="button" onClick={()=>syncNow()} className="btn mt-4 ml-2"><CheckCircle2/>Apply</button></form>
<div className="card mt-5"><h2 className="title"><Eye/>Line items</h2><div className="grid md:grid-cols-3 gap-3 mt-4"><select className="input" value={city} onChange={e=>setCity(e.target.value)}><option>All</option>{cities.map(c=><option key={c.city}>{c.city}</option>)}</select><select className="input" value={state} onChange={e=>setState(e.target.value)}><option>All</option><option>active</option><option>paused</option></select><select className="input" value={trigger} onChange={e=>setTrigger(e.target.value)}><option>All</option>{TRIGGER_TYPES.map(t=><option key={t.value} value={t.value}>{t.value}</option>)}</select></div></div>
<div className="card mt-5 overflow-x-auto"><table className="table"><thead><tr>{['Preview','Creative','City','Trigger','State','Action','Weather/confidence','Decision reason','Condition','Updated'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><img src={item.creative_image_url} className="h-16 w-28 object-cover rounded-xl"/></td><td className="font-bold">{item.creative_name}</td><td>{item.city}</td><td><TriggerBadge t={item.trigger_type}/></td><td><span className={item.state==='active'?'badge-active':'badge-paused'}>{item.state}</span></td><td><button onClick={()=>toggleItem(item)} className={item.state==='active'?'btn-danger':'btn'}>{item.state==='active'?'Pause':'Activate'}</button></td><td className="text-xs">temp {item.last_weather_temperature??'-'}°C / feels {item.last_weather_apparent_temperature??'-'}°C<br/>rain {item.last_weather_precipitation??'-'} / wind {item.last_weather_wind_speed??'-'}<br/><b>{confidenceText(item.last_decision_confidence)}</b></td><td className="min-w-80 text-xs">{item.last_decision_reason}</td><td className="min-w-96">{editing===item.id?<div><textarea className="input font-mono text-xs" rows="5" value={editConfig} onChange={e=>setEditConfig(e.target.value)}/><button className="btn mt-2" onClick={()=>saveConfig(item)}>Save</button></div>:<div className="flex gap-2"><code className="text-xs">{JSON.stringify(item.condition_config)}</code><button className="btn" onClick={()=>{setEditing(item.id);setEditConfig(json(item.condition_config))}}><Pencil size={14}/></button></div>}</td><td>{fmt(item.updated_at)}</td></tr>)}</tbody></table></div>
<div className="grid lg:grid-cols-2 gap-5 mt-5"><div className="card overflow-x-auto"><h2 className="title">Recent transition logs</h2><table className="table"><thead><tr>{['City','Creative','Trigger','Previous','New','Reason','Confidence','Changed'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{l.city}</td><td>{l.creative_name}</td><td>{l.trigger_name}</td><td>{l.previous_state}</td><td>{l.new_state}</td><td className="min-w-80 text-xs">{l.reason}</td><td>{confidenceText(l.confidence)}</td><td>{fmt(l.created_at)}</td></tr>)}</tbody></table></div><div className="card overflow-x-auto"><h2 className="title"><MessageCircle/>Customer weather feedback</h2><table className="table"><thead><tr>{['City','Shown','Answer','Actual','Note','Time'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{feedback.map(f=><tr key={f.id}><td>{f.city}</td><td>{f.shown_trigger_type}<br/><span className="text-xs">{f.shown_creative_name}</span></td><td>{f.answer}</td><td>{f.actual_weather}</td><td>{f.user_note}</td><td>{fmt(f.created_at)}</td></tr>)}</tbody></table></div></div>
</main></div>}
function moodFor(trigger,weather){const cold=trigger?.includes('cold')||(weather?.apparentTemperature<=18),rain=trigger?.includes('rain'),hot=trigger?.includes('hot'),wind=weather?.windSpeed>=18&&!rain&&!hot&&!cold;return {rain,hot,cold,wind,title:rain?'Rainy-day refreshment':hot?'Beat the heat beautifully':cold?'Cool breeze, cozy sip':wind?'Breezy refreshment':'Refresh anytime',sub:rain?'Made for a drizzly moment.':hot?'Cold, crisp and ready for the sun.':cold?'Smooth refreshment for a cool breeze.':wind?'Light refreshment for a breezy day.':'Your everyday refreshment, always ready.',bg:rain?'from-sky-200 via-indigo-100 to-slate-100':hot?'from-orange-200 via-yellow-100 to-cyan-100':cold?'from-blue-100 via-slate-100 to-white':wind?'from-emerald-100 via-cyan-50 to-lime-50':'from-cyan-100 via-emerald-50 to-yellow-50'}}
function WeatherAnimation({m}){return <div className="anim-layer">{m.rain&&<div className="rain">{Array.from({length:46}).map((_,i)=><i key={i}/>)}</div>}{m.hot&&<div className="heat"><Sun size={220}/><b/><b/><b/></div>}{m.cold&&<div className="coldwind">{Array.from({length:20}).map((_,i)=><i key={i}/>)}</div>}{m.wind&&<div className="leaves">{Array.from({length:16}).map((_,i)=><i key={i}>🍃</i>)}</div>}{!m.rain&&!m.hot&&!m.cold&&!m.wind&&<div className="leaves soft">{Array.from({length:14}).map((_,i)=><i key={i}>✨</i>)}</div>}</div>}
function FeedbackPopup({item,city,onClose}){const[actual,setActual]=useState(''),[note,setNote]=useState('');async function submit(answer){await supabase.from('user_weather_feedback').insert({city,shown_trigger_type:item?.trigger_type,shown_creative_name:item?.creative_name,question:'Is the weather shown by our system correct?',answer,actual_weather:actual,user_note:note});onClose()}return <div className="feedback-pop"><button className="float-right text-slate-400" onClick={onClose}>×</button><b>Is the weather matching your place?</b><p className="text-sm text-slate-600 mt-1">Help CoolSip improve context-aware ads.</p><select className="input mt-2" value={actual} onChange={e=>setActual(e.target.value)}><option value="">What is it like there?</option><option>Raining</option><option>Sunny / Hot</option><option>Cold / Windy</option><option>Normal</option><option>Not sure</option></select><input className="input mt-2" placeholder="Optional note" value={note} onChange={e=>setNote(e.target.value)}/><div className="flex gap-2 mt-3"><button className="btn-primary flex-1" onClick={()=>submit('yes')}>Yes</button><button className="btn flex-1" onClick={()=>submit('no')}>No</button></div></div>}
function PublicPage(){const[cities,setCities]=useState([]),[city,setCity]=useState(''),[item,setItem]=useState(null),[campaign,setCampaign]=useState(null),[weather,setWeather]=useState(null),[decision,setDecision]=useState(null),[detected,setDetected]=useState(''),[showFeedback,setShowFeedback]=useState(false)
async function loadBase(){const{data:c}=await supabase.from('cities').select('*').eq('is_active',true).order('city');const{data:camp}=await supabase.from('campaigns').select('*').eq('id',campaignId).maybeSingle();setCities(c||[]);setCampaign(camp);if(!city&&c?.length){if(navigator.geolocation)navigator.geolocation.getCurrentPosition(p=>{const cur={latitude:p.coords.latitude,longitude:p.coords.longitude},near=[...c].sort((a,b)=>hav(cur,a)-hav(cur,b))[0];setDetected(`Nearest city selected: ${near.city}`);setCity(near.city)},()=>setCity(c[0].city),{timeout:7000,maximumAge:600000});else setCity(c[0].city)}}
async function loadCity(){if(!city)return;const c=cities.find(x=>x.city===city);if(c){try{const w=await fetchWeather(c.latitude,c.longitude);setWeather(w);setDecision(getWeatherRecommendation(w))}catch{}}if(campaign?.state==='paused'){setItem(null);return}const{data}=await supabase.from('line_items').select('*').eq('city',city).eq('state','active').maybeSingle();setItem(data)}
useEffect(()=>{loadBase();const ch=supabase.channel('public-live').on('postgres_changes',{event:'*',schema:'public',table:'cities'},loadBase).on('postgres_changes',{event:'*',schema:'public',table:'line_items'},loadCity).on('postgres_changes',{event:'*',schema:'public',table:'campaigns'},loadBase).subscribe();return()=>supabase.removeChannel(ch)},[])
useEffect(()=>{loadCity()},[city,cities.length,campaign?.state])
useEffect(()=>{if(item){const t=setTimeout(()=>setShowFeedback(true),9000);return()=>clearTimeout(t)}},[item?.id])
const m=moodFor(item?.trigger_type||decision?.recommended_trigger_type,weather)
return <div className={`min-h-screen overflow-hidden bg-gradient-to-br ${m.bg}`}><WeatherAnimation m={m}/><nav className="max-w-7xl mx-auto px-5 py-5 flex justify-between relative z-10"><div className="flex items-center gap-3"><div className="logo"><Droplets className="text-cyan-600"/></div><b className="text-2xl">CoolSip</b></div><div className="hidden md:flex gap-6 font-semibold"><a>Flavours</a><a>Offers</a><a>Stores</a></div><div className="flex gap-2"><button className="btn"><UserCircle size={18}/>Account</button><a className="btn opacity-60" href="/admin">Admin</a></div></nav><main className="max-w-7xl mx-auto px-5 grid lg:grid-cols-2 gap-10 items-center relative z-10"><section className="py-10"><p className="pill"><Sparkles size={16}/> Live context-aware campaign</p><h1 className="hero">{m.title}</h1><p className="mt-5 text-xl text-slate-700 max-w-xl">{m.sub} Pick your city, and CoolSip adapts the campaign moment instantly.</p><div className="mt-7 flex gap-3"><button className="btn-primary text-base px-8"><ShoppingBag/>Buy now</button><button className="btn text-base px-8">Explore flavours</button></div><div className="mt-8 max-w-md glass"><label className="label">Location</label><select className="input mt-2 bg-white" value={city} onChange={e=>setCity(e.target.value)}>{cities.map(c=><option key={c.city}>{c.city}</option>)}</select>{detected&&<p className="text-sm mt-2 text-slate-600">{detected}. You can change manually.</p>}</div></section><section className="relative min-h-[560px] grid place-items-center"><div className="creative-card">{campaign?.state==='paused'?<div className="p-10 text-center"><h2 className="text-3xl font-black">We’ll be back soon</h2><p>Campaign is paused.</p></div>:item?<><div className="relative overflow-hidden rounded-[2rem]"><img src={item.creative_image_url} className="w-full h-96 object-cover hover:scale-105 transition duration-700"/><div className="absolute top-4 left-4 rounded-full bg-white/90 px-4 py-2 font-black">{city}</div></div><h2 className="text-4xl font-black mt-5">{item.creative_name}</h2><p className="mt-2 text-slate-600">A CoolSip recommendation made for this moment.</p><div className="mt-5 flex gap-3"><button className="btn-primary flex-1"><ShoppingBag/>Buy now</button><button className="btn">Save offer</button></div></>:<div className="p-10 text-center"><h2 className="text-2xl font-black">No active creative yet</h2><p>Admin can wait for auto sync or activate one.</p></div>}</div></section></main>{showFeedback&&item&&<FeedbackPopup item={item} city={city} onClose={()=>setShowFeedback(false)}/>}</div>}
function App(){const[session,setSession]=useState(null);useEffect(()=>{if(supabase)supabase.auth.getSession().then(({data})=>setSession(data.session))},[]);if(!isSupabaseConfigured)return <EmptyConfig/>;if(location.pathname.startsWith('/admin'))return session?<Dashboard/>:<Login onLogin={()=>supabase.auth.getSession().then(({data})=>setSession(data.session))}/>;return <PublicPage/>}
createRoot(document.getElementById('root')).render(<App />)
